# Generated by Django 5.2.7 on 2025-12-04 13:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brand', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nume', models.CharField(max_length=400)),
                ('tara_origine', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categorie', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nume', models.CharField(max_length=200)),
                ('descriere', models.TextField()),
                ('imagine_categorie', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=10)),
                ('prenume', models.CharField(max_length=10)),
                ('cnp', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('tip_mesaj', models.CharField(choices=[('', 'neselectat'), ('reclamatie', 'reclamatie'), ('intrebare', 'intrebare'), ('review', 'review'), ('cerere', 'cerere'), ('programare', 'programare')], max_length=20)),
                ('subiect', models.CharField(max_length=100)),
                ('mesaj', models.TextField()),
                ('varsta', models.CharField(max_length=20)),
                ('min_zile', models.PositiveIntegerField()),
                ('urgent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(max_length=255)),
                ('oras', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('cod_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_material', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nume', models.CharField(max_length=50)),
                ('eco', models.BooleanField(default=True)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=150)),
                ('prenume', models.CharField(max_length=150, null=True)),
                ('data_nastere', models.DateField(null=True)),
                ('tip_user', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10)),
                ('nr_comenzi', models.IntegerField(default=0)),
                ('tara', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cod', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email_confirmat', models.BooleanField(default=False)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produs', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('pret', models.FloatField()),
                ('in_stoc', models.BooleanField(default=True)),
                ('data_adaugare', models.DateField(auto_now_add=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='produse/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse_brand', to='magazin_haine.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='magazin_haine.categorie')),
                ('materiale', models.ManyToManyField(to='magazin_haine.material')),
            ],
        ),
        migrations.CreateModel(
            name='Colectie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_colectie', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nume', models.CharField(max_length=100)),
                ('sezon', models.CharField(choices=[('p-v', 'primavara-vara'), ('t-i', 'toamna-iarna'), ('i', 'iarna'), ('p', 'primavara'), ('v', 'vara'), ('t', 'toamna')], max_length=100)),
                ('an', models.IntegerField()),
                ('produs', models.ManyToManyField(to='magazin_haine.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Promotie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, max_length=50)),
                ('data_creare', models.DateField(auto_now_add=True)),
                ('data_expirare', models.DateField()),
                ('activ', models.BooleanField(default=True)),
                ('procent_reducere', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('categorii_valabile', models.ManyToManyField(related_name='promotii_asociate', to='magazin_haine.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='VariantaProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_varianta', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('culoare', models.CharField(choices=[('albastru', 'albastru'), ('alb', 'alb'), ('negru', 'negru'), ('rosu', 'rosu'), ('galben', 'galben'), ('roz', 'roz'), ('gri', 'gri'), ('maro', 'maro')], max_length=10)),
                ('marime', models.CharField(max_length=3)),
                ('stoc', models.IntegerField()),
                ('imagine_varianta', models.ImageField(blank=True, null=True, upload_to='produse/')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variante', to='magazin_haine.produs')),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comanda', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('pret', models.FloatField(default=0)),
                ('metoda_plata', models.CharField(choices=[('ramburs', 'ramburs'), ('card', 'card')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizatori', to=settings.AUTH_USER_MODEL)),
                ('produs', models.ManyToManyField(to='magazin_haine.variantaprodus')),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizualizari_produse', to='magazin_haine.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vizualizari_utilizatori', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_vizualizare'],
            },
        ),
    ]
