# Generated by Django 5.2.7 on 2025-12-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_haine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vizualizare',
            options={},
        ),
    ]
