# Generated by Django 5.2.7 on 2025-12-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_haine', '0002_alter_vizualizare_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vedea oferta speciala')]},
        ),
    ]
