# Generated by Django 6.0.2 on 2026-02-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin_haine', '0004_customuser_blocat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='imagine_categorie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='produs',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
